GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/
content-type: application/json
Authorization: Bearer

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer
{
"title": "Laurin koodiblogi", 
"author": "Lauri Maila", 
"url": "laurimaila.com", 
"likes": 42
}

###
PUT http://localhost:3003/api/
content-type: application/json

{ 
"title": "Laurin parempi blogi",
"likes": 42
}